<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="contenthub" nsURI="https://aemcontenthub.eniware-systems.de/ns/contenthub"
    nsPrefix="chub">
  <eClassifiers xsi:type="ecore:EDataType" name="Path" instanceClassName="java.nio.file.Path"/>
  <eClassifiers xsi:type="ecore:EClass" name="Package">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="my.content" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="group" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="de.enithing"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="A new package"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="author" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="admin"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="1.0.0"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contexts" upperBound="-1"
        eType="#//RootContext" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Context">
    <eOperations name="getRootContext" lowerBound="1" eType="#//RootContext"/>
    <eOperations name="getRelatedContexts" upperBound="-1" eType="#//Context"/>
    <eOperations name="getRelatedPolicies" upperBound="-1" eType="#//ContextPolicy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="childContexts" upperBound="-1"
        eType="#//ChildContext" containment="true" eOpposite="#//ChildContext/parentContext"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contentFragmentModels"
        upperBound="-1" eType="#//contentfragment/ContentFragmentModel" containment="true"
        eOpposite="#//contentfragment/ContentFragmentModel/context"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contentFragments" upperBound="-1"
        eType="#//contentfragment/ContentFragmentInstance" containment="true" eOpposite="#//contentfragment/ContentFragmentInstance/context"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="policies" upperBound="-1"
        eType="#//ContextPolicy" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RootContext" eSuperTypes="#//Context">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="jcrRootPath" lowerBound="1"
        eType="#//Path" defaultValueLiteral="/jcr_root"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChildContext" eSuperTypes="#//Context">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentContext" lowerBound="1"
        eType="#//Context" eOpposite="#//Context/childContexts"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="relativePath" lowerBound="1"
        eType="#//Path" defaultValueLiteral="/child"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContextPolicy" abstract="true" interface="true"/>
  <eSubpackages name="contentfragment" nsURI="https://aemcontenthub.eniware-systems.de/ns/contentfragments"
      nsPrefix="chub">
    <eClassifiers xsi:type="ecore:EClass" name="ContentFragmentModel">
      <eOperations name="getAllChildren" upperBound="-1">
        <eGenericType eClassifier="#//contentfragment/ContentFragmentFieldType">
          <eTypeArguments/>
        </eGenericType>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="fields" upperBound="-1"
          eType="#//contentfragment/ContentFragmentFieldType" containment="true" eKeys="#//contentfragment/ContentFragmentFieldType/propertyName"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="context" lowerBound="1"
          eType="#//Context" eOpposite="#//Context/contentFragmentModels"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          iD="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ContentFragmentFieldType" abstract="true">
      <eTypeParameters name="TValue">
        <eBounds eClassifier="#//contentfragment/ContentFragmentFieldValue"/>
      </eTypeParameters>
      <eOperations name="createEmptyValue" lowerBound="1">
        <eGenericType eTypeParameter="#//contentfragment/ContentFragmentFieldType/TValue"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="propertyName" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          iD="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="fieldLabel" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ContentFragmentInstance">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          iD="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="model" lowerBound="1"
          eType="#//contentfragment/ContentFragmentModel"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="fields" upperBound="-1"
          eType="#//contentfragment/ContentFragmentFieldInstance" changeable="false"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="context" lowerBound="1"
          eType="#//Context" eOpposite="#//Context/contentFragments"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ContentFragmentFieldInstance">
      <eStructuralFeatures xsi:type="ecore:EReference" name="fieldtype" lowerBound="1"
          eType="#//contentfragment/ContentFragmentFieldType"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1"
          eType="#//contentfragment/ContentFragmentFieldValue" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SimpleFieldType" abstract="true" interface="true">
      <eTypeParameters name="TValue">
        <eBounds eClassifier="#//contentfragment/ContentFragmentFieldValue"/>
      </eTypeParameters>
      <eGenericSuperTypes eClassifier="#//contentfragment/ContentFragmentFieldType">
        <eTypeArguments eTypeParameter="#//contentfragment/SimpleFieldType/TValue"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="GroupFieldType" abstract="true" interface="true">
      <eTypeParameters name="TValue">
        <eBounds eClassifier="#//contentfragment/ContentFragmentFieldValue"/>
      </eTypeParameters>
      <eStructuralFeatures xsi:type="ecore:EReference" name="fields" upperBound="-1"
          eType="#//contentfragment/SimpleFieldType" containment="true" eKeys="#//contentfragment/ContentFragmentFieldType/propertyName"/>
      <eGenericSuperTypes eClassifier="#//contentfragment/ContentFragmentFieldType">
        <eTypeArguments eTypeParameter="#//contentfragment/GroupFieldType/TValue"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ContentFragmentFieldValue" abstract="true"
        interface="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="IdContentFragmentFieldType" abstract="true"
        interface="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="AllowedContentFragmentModelPolicy"
        eSuperTypes="#//ContextPolicy">
      <eStructuralFeatures xsi:type="ecore:EReference" name="models" upperBound="-1"
          eType="#//contentfragment/ContentFragmentModel"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MultiFieldType" abstract="true" interface="true">
      <eTypeParameters name="TValue">
        <eBounds eClassifier="#//contentfragment/ContentFragmentFieldValue"/>
      </eTypeParameters>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="allowMultiple" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="false"/>
      <eGenericSuperTypes eClassifier="#//contentfragment/SimpleFieldType">
        <eTypeArguments eTypeParameter="#//contentfragment/MultiFieldType/TValue"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eSubpackages name="corefields" nsURI="https://aemcontenthub.eniware-systems.de/ns/contentfragments/corefields"
        nsPrefix="chub">
      <eClassifiers xsi:type="ecore:EClass" name="Number">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="placeholderText" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eGenericSuperTypes eClassifier="#//contentfragment/SimpleFieldType">
          <eTypeArguments eClassifier="#//contentfragment/corefields/NumberValue"/>
        </eGenericSuperTypes>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="NumberValue" eSuperTypes="#//contentfragment/ContentFragmentFieldValue">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
            defaultValueLiteral="0"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="SingleLineText">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="placeholderText" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxLength" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
            defaultValueLiteral="255"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="required" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
            defaultValueLiteral="false"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="unique" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
            defaultValueLiteral="false"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="translatable" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
            defaultValueLiteral="false"/>
        <eGenericSuperTypes eClassifier="#//contentfragment/MultiFieldType">
          <eTypeArguments eClassifier="#//contentfragment/corefields/TextValue"/>
        </eGenericSuperTypes>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="MultiLineTextType">
        <eLiterals name="RichText" literal="text/html"/>
        <eLiterals name="Markdown" value="1" literal="text/markdown"/>
        <eLiterals name="PlainText" value="2" literal="text/plain"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="MultiLineText">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultType" lowerBound="1"
            eType="#//contentfragment/corefields/MultiLineTextType" defaultValueLiteral="text/html"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="allowFragmentReference"
            lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
            defaultValueLiteral="false"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="required" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
            defaultValueLiteral="false"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="translatable" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
            defaultValueLiteral="false"/>
        <eGenericSuperTypes eClassifier="#//contentfragment/MultiFieldType">
          <eTypeArguments eClassifier="#//contentfragment/corefields/TextValue"/>
        </eGenericSuperTypes>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TextValue" eSuperTypes="#//contentfragment/ContentFragmentFieldValue">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Tab">
        <eGenericSuperTypes eClassifier="#//contentfragment/GroupFieldType">
          <eTypeArguments eClassifier="#//contentfragment/ContentFragmentFieldValue"/>
        </eGenericSuperTypes>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ContentFragmentReference">
        <eGenericSuperTypes eClassifier="#//contentfragment/MultiFieldType">
          <eTypeArguments eClassifier="#//contentfragment/corefields/ContentFragmentReferenceValue"/>
        </eGenericSuperTypes>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ContentFragmentReferenceValue" eSuperTypes="#//contentfragment/ContentFragmentFieldValue">
        <eStructuralFeatures xsi:type="ecore:EReference" name="fragments" upperBound="-1"
            eType="#//contentfragment/ContentFragmentInstance"/>
      </eClassifiers>
    </eSubpackages>
  </eSubpackages>
</ecore:EPackage>
