/**
 */
package de.enithing.fragmenthub.model.contentfragment.provider;

import de.enithing.fragmenthub.model.contentfragment.provider.ExtendedContentFragmentFieldInstanceItemProvider;
import de.enithing.fragmenthub.model.contentfragment.provider.ExtendedContentFragmentInstanceItemProvider;
import de.enithing.fragmenthub.model.contentfragment.util.ContentFragmentAdapterFactory;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class ContentFragmentItemProviderAdapterFactory extends ContentFragmentAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ContentFragmentItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.enithing.fragmenthub.model.contentfragment.ContentFragmentModelSet} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ContentFragmentModelSetItemProvider contentFragmentModelSetItemProvider;

	/**
	 * This creates an adapter for a {@link de.enithing.fragmenthub.model.contentfragment.ContentFragmentModelSet}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createContentFragmentModelSetAdapter() {
		if (contentFragmentModelSetItemProvider == null) {
			contentFragmentModelSetItemProvider = new ContentFragmentModelSetItemProvider(this);
		}

		return contentFragmentModelSetItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.enithing.fragmenthub.model.contentfragment.ContentFragmentModel} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ContentFragmentModelItemProvider contentFragmentModelItemProvider;

	/**
	 * This creates an adapter for a {@link de.enithing.fragmenthub.model.contentfragment.ContentFragmentModel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createContentFragmentModelAdapter() {
		if (contentFragmentModelItemProvider == null) {
			contentFragmentModelItemProvider = new ContentFragmentModelItemProvider(this);
		}

		return contentFragmentModelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.enithing.fragmenthub.model.contentfragment.ContentFragmentInstance} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ContentFragmentInstanceItemProvider contentFragmentInstanceItemProvider;

	/**
	 * This creates an adapter for a {@link de.enithing.fragmenthub.model.contentfragment.ContentFragmentInstance}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc --> 
	 */
	@Override
	public Adapter createContentFragmentInstanceAdapter() {
		if (contentFragmentInstanceItemProvider == null) {
			// This was changed to get the extended provider.
			contentFragmentInstanceItemProvider = new ExtendedContentFragmentInstanceItemProvider(this);
		}

		return contentFragmentInstanceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.enithing.fragmenthub.model.contentfragment.ContentFragmentFieldInstance} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ContentFragmentFieldInstanceItemProvider contentFragmentFieldInstanceItemProvider;

	/**
	 * This creates an adapter for a {@link de.enithing.fragmenthub.model.contentfragment.ContentFragmentFieldInstance}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 */
	@Override
	public Adapter createContentFragmentFieldInstanceAdapter() {
		if (contentFragmentFieldInstanceItemProvider == null) {
			// This was changed to get the extended provider.
			contentFragmentFieldInstanceItemProvider = new ExtendedContentFragmentFieldInstanceItemProvider(this);
		}

		return contentFragmentFieldInstanceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.enithing.fragmenthub.model.contentfragment.AllowedContentFragmentModelPolicy} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AllowedContentFragmentModelPolicyItemProvider allowedContentFragmentModelPolicyItemProvider;

	/**
	 * This creates an adapter for a {@link de.enithing.fragmenthub.model.contentfragment.AllowedContentFragmentModelPolicy}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAllowedContentFragmentModelPolicyAdapter() {
		if (allowedContentFragmentModelPolicyItemProvider == null) {
			allowedContentFragmentModelPolicyItemProvider = new AllowedContentFragmentModelPolicyItemProvider(this);
		}

		return allowedContentFragmentModelPolicyItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void dispose() {
		if (contentFragmentModelSetItemProvider != null) contentFragmentModelSetItemProvider.dispose();
		if (contentFragmentModelItemProvider != null) contentFragmentModelItemProvider.dispose();
		if (contentFragmentInstanceItemProvider != null) contentFragmentInstanceItemProvider.dispose();
		if (contentFragmentFieldInstanceItemProvider != null) contentFragmentFieldInstanceItemProvider.dispose();
		if (allowedContentFragmentModelPolicyItemProvider != null) allowedContentFragmentModelPolicyItemProvider.dispose();
	}

}
