#!/usr/bin/env bash

SCRIPTPATH="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"

echo $SCRIPTPATH

JAR_FILE=$(realpath $(ls ${SCRIPTPATH}/../de.enithing.contenthub.generator.cli/target/de.enithing.contenthub.generator.cli-*-jar-with-dependencies.jar 2> /dev/null) 2> /dev/null)
OUT_DIR=$(mktemp)
ZIP_FILE=$HOME/package.zip
rm -rf $OUT_DIR
mkdir $OUT_DIR

trap "rm -rf $OUT_DIR" EXIT

java -jar $JAR_FILE $@ -o $OUT_DIR || { exit 1; }

pushd $OUT_DIR
zip -r $ZIP_FILE ./*
popd
